apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: loraserverio
  annotations:
    volume.beta.kubernetes.io/storage-class: managed-premium
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 50Gi
