apiVersion: v1
kind: Service
metadata:
  namespace: loraserverio
  name: lora-server
  labels:
    component: lora-server
spec:
  type: ClusterIP
  selector:
    component: lora-server
  ports:
    - port: 1700
      name: udp
