apiVersion: v1
kind: Service
metadata:
  namespace: loraserverio
  name: postgres
  labels:
    app: postgres
spec:
  clusterIP: None
  selector:
    component: postgres
  ports:
    - port: 5432
      name: http
