apiVersion: v1
kind: Service
metadata:
  namespace: loraserverio
  name: influx-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: influx
  ports:
    - port: 8086
      targetPort: 8086
      name: http
    - port: 8083
      targetPort: 8083
      name: admin
