apiVersion: v1
kind: Service
metadata:
  namespace: loraserverio
  name: eclipse-moquitto
  labels:
    component: eclipse-moquitto
spec:
  type: ClusterIP
  selector:
    component: eclipse-moquitto
  ports:
    - port: 1700
      name: udp
