apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: loraserverio
  name: lora-app-server
  labels:
    component: lora-app-server
spec:
  replicas: 1
  selector:
    matchLabels:
      component: lora-app-server
  template:
    metadata:
      labels:
        component: lora-app-server
    spec:
      initContainers:
        - name: wait-services
          image: busybox
          command: ['sh', '-c', 'until nslookup postgres.loraserverio.svc.cluster.local; do echo waiting service start; sleep 2; done;']
      containers:
        - name: lora-app-server
          image: loraserver/lora-app-server:3
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: lora-app-server
              mountPath: /etc/lora-app-server
      volumes:
        - name: lora-app-server
          configMap:
            name: lora-app-server-config
