apiVersion: v1
kind: Service
metadata:
  namespace: loraserverio
  name: lora-app-server
  labels:
    component: lora-app-server
spec:
  type: ClusterIP
  selector:
    component: lora-app-server
  ports:
    - port: 8080
      name: http
