apiVersion: v1
kind: ConfigMap
metadata:
  namespace: loraserverio
  name: lora-server-config
data:
  loraserver.toml: |
    # See https://www.loraserver.io/loraserver/install/config/ for a full
    # configuration example and documentation.
    #
    # This file is for the EU868 band. See the examples/ folder for more
    # configuration examples.

    [postgresql]
    dsn="postgres://loraserver_ns:loraserver_ns@postgres/loraserver_ns?sslmode=disable"

    [redis]
    url="redis://redis-cluster-ip-service:6379"

    [network_server]
    net_id="000000"

    [network_server.band]
    name="EU_863_870"

    [network_server.network_settings]

    [[network_server.network_settings.extra_channels]]
    frequency=867100000
    min_dr=0
    max_dr=5

    [[network_server.network_settings.extra_channels]]
    frequency=867300000
    min_dr=0
    max_dr=5

    [[network_server.network_settings.extra_channels]]
    frequency=867500000
    min_dr=0
    max_dr=5

    [[network_server.network_settings.extra_channels]]
    frequency=867700000
    min_dr=0
    max_dr=5

    [[network_server.network_settings.extra_channels]]
    frequency=867900000
    min_dr=0
    max_dr=5

    [network_server.gateway.backend.mqtt]
    server="tcp://eclipse-moquitto:1883"

    [join_server.default]
    server="http://appserver:8003"

