apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: loraserverio
  name: lora-server
  labels:
    component: lora-server
spec:
  replicas: 2
  selector:
    matchLabels:
      component: lora-server
  template:
    metadata:
      labels:
        component: lora-server
    spec:
      initContainers:
        - name: wait-services
          image: busybox
          command: ['sh', '-c', 'until nslookup postgres.loraserverio.svc.cluster.local; do echo waiting service start; sleep 2; done;']
      containers:
        - name: lora-server
          image: loraserver/loraserver:3
          volumeMounts:
            - name: lora-server
              mountPath: /etc/loraserver
      volumes:
        - name: lora-server
          configMap:
            name: lora-server-config
