apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: loraserverio
  name: postgres
spec:
  replicas: 2
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:12-alpine
          env:
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: admin
            - name: POSTGRES_DB
              value: public
          ports:
            - containerPort: 5432
              name: http
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-data
