apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: loraserverio
  name: postgres-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 50Gi
